---
- name: mkdir zabbix
  win_file: 
    path: "{{ zabbix_win_dir }}/log"
    state: directory
- name: 复制agent文件
  win_copy:
    src: zabbix_agent2-{{zabbix_version}}-windows-amd64.zip
    dest: "{{ zabbix_win_dir }}/"
- name: 解压agent文件
  win_unzip: 
    src: "{{ zabbix_win_dir }}/zabbix_agent2-{{zabbix_version}}-windows-amd64.zip"
    dest: "{{ zabbix_win_dir }}/"
- name: 复制配置文件到解压后的目录
  win_template:
    src: zabbix_agent2_win.conf
    dest: "{{ zabbix_win_dir }}/conf/"
- name: 注册agent2服务
  win_command: "{{ zabbix_win_dir }}/bin/zabbix_agent2.exe -i -c {{ zabbix_win_dir }}/conf/zabbix_agent2_win.conf"
  args:
    chdir: "{{ zabbix_win_dir }}"
- name: 启动agent2服务
  win_command: "{{ zabbix_win_dir }}/bin/zabbix_agent2.exe -s -c {{ zabbix_win_dir }}/conf/zabbix_agent2_win.conf"
  args:
    chdir: "{{ zabbix_win_dir }}"
